# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Covariance matrix of a vector \code{x} observed at \code{n} consecutive
#' timepoints.
#'
#' Creates the covariance matrix of an AR(1) process with parameters \code{rho}
#' and \code{sigma}, observed at \code{n} consecutive time points. The process
#' is assumed to be in stationarity and have Gaussian errors.
#' @param n An integer greater than or equal to 1.
#' @param rho A real number strictly less than 1 in absolute value.
#' @param sigma A positive real number.
#' @return A matrix with \code{n} rows and \code{n} columns.
#' @export
ar1_cov_consecutive <- function(n, rho, sigma) {
    .Call(`_irregulAR1_ar1_cov_consecutive`, n, rho, sigma)
}

#' Covariance matrix of vector x observed at (irregularly spaced) times times.
#'
#' Creates the covariance matrix of an AR(1) process with parameters \code{rho}
#' and \code{sigma}, observed at the time points in the vector \code{times}.
#' The process is assumed to be in stationarity and have Gaussian errors.
#' @param times An vector of positive integers, preferably ordered.
#' @param rho A real number strictly less than 1 in absolute value.
#' @param sigma A positive real number.
#' @return A square matrix with \code{length(times)} rows.
#' @export
ar1_cov_irregular <- function(times, rho, sigma) {
    .Call(`_irregulAR1_ar1_cov_irregular`, times, rho, sigma)
}

#' Partial covariance matrix of vectors x and y observed at  (irregularly
#' spaced) times times1 and times2, respectively.
#'
#' Creates the cross-covariance matrix of an AR(1) process with parameters
#' \code{rho} and \code{sigma}, observed at (positive) integer times
#' \code{times1} and \code{times2}.  The process is assumed to be in
#' stationarity and have Gaussian errors.
#' @param times1 An vector of positive integers, preferably ordered.
#' @param times2 An vector of positive integers, preferably ordered.
#' @param rho A real number strictly less than 1 in absolute value.
#' @param sigma A positive real number.
#' @return A matrix with \code{n} rows and \code{n} columns.
#' @export
ar1_cross_cov <- function(times1, times2, rho, sigma) {
    .Call(`_irregulAR1_ar1_cross_cov`, times1, times2, rho, sigma)
}

#' Upper triangular Cholesky factorization of covariance matrix of a vector x
#' observed at times times.
#' @export
ar1_cov_chol_irregular <- function(times, rho, sigma) {
    .Call(`_irregulAR1_ar1_cov_chol_irregular`, times, rho, sigma)
}

#' Precision matrix of vector x observed at n consecutive times.
#' @export
ar1_prec_consecutive <- function(n, rho, sigma) {
    .Call(`_irregulAR1_ar1_prec_consecutive`, n, rho, sigma)
}

#' Precision matrix
#' @export
ar1_prec_irregular <- function(times, rho, sigma) {
    .Call(`_irregulAR1_ar1_prec_irregular`, times, rho, sigma)
}

#' Banded Cholesky decomposition
#' @export
band1chol <- function(Q) {
    .Call(`_irregulAR1_band1chol`, Q)
}

#' Cholesky decomposition of tridiagonal matrix
#' If Q is a tridiagonal matrix and Q = LL' = U'U, this function returns L'=U.
#' See Algorithm 2.9 of Rue & Held
#' @export
trid_chol <- function(Q) {
    .Call(`_irregulAR1_trid_chol`, Q)
}

