# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Covariance matrix for a stationary Gaussian AR(1) process, observed at
#' consecutive timepoints.
#'
#' Creates the covariance matrix of an AR(1) process with parameters \code{rho}
#' and \code{sigma}, observed at \code{n} consecutive time points. The process
#' is assumed to be in stationarity and have Gaussian errors.
#' @param n An integer greater than or equal to 1.
#' @param rho A real number strictly less than 1 in absolute value.
#' @param sigma A positive real number.
#' @return A matrix with \code{n} rows and \code{n} columns.
#' @export
ar1_cov_consecutive <- function(n, rho, sigma) {
    .Call(`_irregulAR1_ar1_cov_consecutive`, n, rho, sigma)
}

#' Covariance matrix for a stationary Gaussian AR(1) process, observed at
#' irregularly spaced time points.
#'
#' Creates the covariance matrix of an AR(1) process with parameters \code{rho}
#' and \code{sigma}, observed at the time points in the vector \code{times}.
#' The process is assumed to be in stationarity and have Gaussian errors.
#' @param times An vector of positive integers, preferably ordered.
#' @param rho A real number strictly less than 1 in absolute value.
#' @param sigma A positive real number.
#' @return A square matrix with \code{length(times)} rows.
#' @export
ar1_cov_irregular <- function(times, rho, sigma) {
    .Call(`_irregulAR1_ar1_cov_irregular`, times, rho, sigma)
}

#' Cross-covariance matrix of a stationary Gaussian AR(1) process.
#'
#' Creates the cross-covariance matrix of an AR(1) process with parameters
#' \code{rho} and \code{sigma}, observed at (positive) integer times
#' \code{times1} and \code{times2}, which may be irregularly spaced. The
#' process is assumed to be in stationarity and have Gaussian errors.
#' @param times1 An vector of positive integers, preferably ordered.
#' @param times2 An vector of positive integers, preferably ordered.
#' @param rho A real number strictly less than 1 in absolute value.
#' @param sigma A positive real number.
#' @return A matrix with \code{length(times2)} rows and \code{length(times1)}
#'   columns.
#' @export
ar1_cross_cov <- function(times1, times2, rho, sigma) {
    .Call(`_irregulAR1_ar1_cross_cov`, times1, times2, rho, sigma)
}

#' Upper triangular Cholesky decomposition for a stationary Gaussian AR(1)
#' process, observed at irregularly spaced time points.
#'
#' Creates the upper triangular Cholesky decomposition matrix of an AR(1)
#' process with parameters \code{rho} and \code{sigma}, observed at the time
#' points in the vector \code{times}. The process is assumed to be in
#' stationarity and have Gaussian errors.
#' @param times An vector of positive integers, preferably ordered.
#' @param rho A real number strictly less than 1 in absolute value.
#' @param sigma A positive real number.
#' @return A square matrix with \code{length(times)} rows.
#' @export
ar1_cov_chol_irregular <- function(times, rho, sigma) {
    .Call(`_irregulAR1_ar1_cov_chol_irregular`, times, rho, sigma)
}

#' Sparse precision matrix for a stationary Gaussian AR(1) process, observed at
#' consecutive timepoints.
#'
#' Creates the precision (inverse covariance) matrix of an AR(1) process with
#' parameters \code{rho} and \code{sigma}, observed at \code{n} consecutive
#' time points. The process is assumed to be in stationarity and have Gaussian
#' errors. The matrix is a tridiagonal band matrix and thus sparse.
#' @param n An integer greater than or equal to 1.
#' @param rho A real number strictly less than 1 in absolute value.
#' @param sigma A positive real number.
#' @return A matrix with \code{n} rows and \code{n} columns.
#' @export
ar1_prec_consecutive <- function(n, rho, sigma) {
    .Call(`_irregulAR1_ar1_prec_consecutive`, n, rho, sigma)
}

#' Precision matrix for a stationary Gaussian AR(1) process, observed at
#' irregularly spaced time points.
#'
#' Creates the precision (inverse covariance) matrix of an AR(1) process with
#' parameters \code{rho} and \code{sigma}, observed at the time points in the
#' vector \code{times}. The process is assumed to be in stationarity and have
#' Gaussian errors.
#' @param times An vector of positive integers, preferably ordered.
#' @param rho A real number strictly less than 1 in absolute value.
#' @param sigma A positive real number.
#' @return A square matrix with \code{length(times)} rows.
#' @export
ar1_prec_irregular <- function(times, rho, sigma) {
    .Call(`_irregulAR1_ar1_prec_irregular`, times, rho, sigma)
}

#' Upper Cholesky decomposition of a tridiagonal matrix.
#'
#' Creates the lower Cholesky decomposition of a tridiagonal matrix. The
#' decomposition will be a sparse lower triangular matrix with non-zero
#' elements only on the main diagonal and the diagonal below it.
#' @param Q A square tridiagonal matrix.
#' @return A sparse square matrix with the same size as the input matrix.
#' @export
chol_tridiag_upper <- function(Q) {
    .Call(`_irregulAR1_chol_tridiag_upper`, Q)
}

#' Backsolve with band 1 upper Cholesky.
#'
#' Backsolve with band 1 upper Cholesky.
#' @param Q A square tridiagonal matrix.
#' @return A sparse square matrix with the same size as the input matrix.
#' @export
band1_backsolve <- function(U, z) {
    .Call(`_irregulAR1_band1_backsolve`, U, z)
}

#' Simulate from a stationary Gaussian AR(1) process.
#'
#' Simulate from a stationary Gaussian AR(1) process at \code{n} consecutive
#' time points.
#' @param n The number of timepoints to simulate for.
#' @param rho A real number strictly less than 1 in absolute value.
#' @param sigma A positive real number.
#' @return A vector of length \code{n} with the process values.
#' @keywords internal
ar1_sim_cpp <- function(n, rho, sigma) {
    .Call(`_irregulAR1_ar1_sim_cpp`, n, rho, sigma)
}

#' Simulate from a stationary Gaussian AR(1) process at irregular times.
#'
#' Simulate from a stationary Gaussian AR(1) process at irregular times.
#' @param n The number of timepoints to simulate for.
#' @param rho A real number strictly less than 1 in absolute value.
#' @param sigma A positive real number.
#' @return A vector of length \code{n} with the process values.
#' @keywords internal
ar1_sim_irregular_cpp <- function(times, rho, sigma) {
    .Call(`_irregulAR1_ar1_sim_irregular_cpp`, times, rho, sigma)
}

